Class {
	#name : #ConfluencePharoLinks,
	#superclass : #Object,
	#instVars : [
		'next',
		'base'
	],
	#category : #'ConfluencePharoAPI-Model'
}

{ #category : #accessing }
ConfluencePharoLinks >> base [

	^ base
]

{ #category : #accessing }
ConfluencePharoLinks >> base: anObject [

	base := anObject
]

{ #category : #accessing }
ConfluencePharoLinks >> next [

	^ next
]

{ #category : #accessing }
ConfluencePharoLinks >> next: anObject [

	next := anObject
]
