Class {
	#name : #ConfluencePharoPageBodyView,
	#superclass : #Object,
	#instVars : [
		'value',
		'representation'
	],
	#category : #'ConfluencePharoAPI-Model'
}

{ #category : #accessing }
ConfluencePharoPageBodyView >> representation [

	^ representation
]

{ #category : #accessing }
ConfluencePharoPageBodyView >> representation: anObject [

	representation := anObject
]

{ #category : #accessing }
ConfluencePharoPageBodyView >> value1 [

	^ value
]

{ #category : #accessing }
ConfluencePharoPageBodyView >> value: anObject [

	value := anObject
]
