Class {
	#name : #ConfluencePharoPageBodyWrite,
	#superclass : #Object,
	#instVars : [
		'representation',
		'value'
	],
	#category : #'ConfluencePharoAPI-Model'
}

{ #category : #accessing }
ConfluencePharoPageBodyWrite >> representation [

	^ representation
]

{ #category : #accessing }
ConfluencePharoPageBodyWrite >> representation: anObject [

	representation := anObject
]

{ #category : #accessing }
ConfluencePharoPageBodyWrite >> value1 [

	^ value
]

{ #category : #accessing }
ConfluencePharoPageBodyWrite >> value: anObject [

	value := anObject
]
