Class {
	#name : #ConfluencePharoSpace,
	#superclass : #Object,
	#instVars : [
		'id',
		'key',
		'alias',
		'name',
		'type'
	],
	#category : #'ConfluencePharoAPI-Model'
}

{ #category : #accessing }
ConfluencePharoSpace >> alias [

	^ alias
]

{ #category : #accessing }
ConfluencePharoSpace >> alias: anObject [

	alias := anObject
]

{ #category : #accessing }
ConfluencePharoSpace >> id [

	^ id
]

{ #category : #accessing }
ConfluencePharoSpace >> id: anObject [

	id := anObject
]

{ #category : #accessing }
ConfluencePharoSpace >> key [

	^ key
]

{ #category : #accessing }
ConfluencePharoSpace >> key: anObject [

	key := anObject
]

{ #category : #accessing }
ConfluencePharoSpace >> name [

	^ name
]

{ #category : #accessing }
ConfluencePharoSpace >> name: anObject [

	name := anObject
]

{ #category : #accessing }
ConfluencePharoSpace >> type [

	^ type
]

{ #category : #accessing }
ConfluencePharoSpace >> type: anObject [

	type := anObject
]
