Class {
	#name : #ConfluencePharoBlogPostAttachement,
	#superclass : #Object,
	#instVars : [
		'id',
		'comment',
		'title',
		'downloadLink',
		'mediaType'
	],
	#category : #'ConfluencePharoAPI-Model'
}

{ #category : #accessing }
ConfluencePharoBlogPostAttachement >> comment [

	^ comment
]

{ #category : #accessing }
ConfluencePharoBlogPostAttachement >> comment: anObject [

	comment := anObject
]

{ #category : #accessing }
ConfluencePharoBlogPostAttachement >> downloadLink [

	^ downloadLink
]

{ #category : #accessing }
ConfluencePharoBlogPostAttachement >> downloadLink: anObject [

	downloadLink := anObject
]

{ #category : #accessing }
ConfluencePharoBlogPostAttachement >> id [

	^ id
]

{ #category : #accessing }
ConfluencePharoBlogPostAttachement >> id: anObject [

	id := anObject
]

{ #category : #accessing }
ConfluencePharoBlogPostAttachement >> mediaType [

	^ mediaType
]

{ #category : #accessing }
ConfluencePharoBlogPostAttachement >> mediaType: anObject [

	mediaType := anObject
]

{ #category : #accessing }
ConfluencePharoBlogPostAttachement >> title [

	^ title
]

{ #category : #accessing }
ConfluencePharoBlogPostAttachement >> title: anObject [

	title := anObject
]
